### ISSUE TITLE
Create `Ephem` object from an `Orbit`

### ISSUE THREAD

**Issue by astrojuanlu** [poliastro/poliastro#1009]
> Actually there is one thing "missing" from my perspective, but not in the docs: A clean, fast and out-of-the-box way of computing an `Ephem` object from an `Orbit` object, e.g. `Ephem.from_orbit(orb, time_stamps, propagator, ...)`.

_Originally posted by @s-m-e in https://github.com/poliastro/poliastro/issues/1008#issuecomment-685949410_

**Comment by Ibnmardanis24** [comment]
Hi, I am new to poliastro but I have had some interest on python and mission analysis for a while now. Getting interested on your repository is only natural. I was wondering if I could solve this issue and get to know your project a bit more in the process.

I'm not a huge advocate for OOP so I'm having a bit of a hard time grasping the exact change that you are proposing here. I get from my own formation in celestial mechanics that the objects 'Orbit' and 'Ephem' only differ by the amount of points in the orbit that you sample. But essentialy an 'Ephem' object is really a colection of 'Orbit' objects, right? I get that the object 'Orbit' already features a method to create it from an 'Ephem' object. So what you would be hoping is for the 'reverse' process. This is possible since a state vector produces a single posible motion.

Following this argument, there are still 2 issues that intringue me: I'm not entirely certain on how many attributes I would need to produce from the info in the Orbit object to fully define an Ephem object. Additionally, my initial approach to generate an Ephem from an Orbit is to propagate the trajectory (either forwards or backwards) a given number of time steps. I guess the parameters of this propagation should be user defined right? Even though they would refer to the same family of Ephem.

Regards.

**Comment by astrojuanlu** [comment]
Hello @Ibnmardanis24 , welcome! Let me answer your questions inline.

> I get from my own formation in celestial mechanics that the objects 'Orbit' and 'Ephem' only differ by the amount of points in the orbit that you sample. But essentialy an 'Ephem' object is really a colection of 'Orbit' objects, right?

You could say that... if you knew what the attractor is :) But in reality `Ephem` objects are a list of coordinates without any attractor attached. Given an attractor, you can assume that it's a collection of **osculating** orbits.

> I get that the object 'Orbit' already features a method to create it from an 'Ephem' object. So what you would be hoping is for the 'reverse' process.

Exactly, and this would be equivalent to `propagate`-ing the `Orbit`, sampling it for the specified `timestamps`, and storing the result in an `Ephem`.

> Additionally, my initial approach to generate an Ephem from an Orbit is to propagate the trajectory (either forwards or backwards) a given number of time steps.

Exactly!

> I guess the parameters of this propagation should be user defined right?

In principle this won't be needed. Let's use the default 2 body propagator, `farnocchia`, with the default parameters.

Therefore, the method signature should be:

```python
class Ephem:
    @classmethod
    def from_orbit(cls, orbit, epochs, plane=Planes.EARTH_EQUATOR,):
        # ...
        # Propagate the orbit
        return cls(coordinates, epochs, plane)
```

Let me know if this is useful enough!

**Comment by Ibnmardanis24** [comment]
Thank you for the very quick response! Yes, that was very instructive, I will get everything set up and reach you out with a PR for next weekend. Then we shall discuss further.

**Comment by CosmicTiger** [comment]
Could you assign this issue to me? Noticing that the other person didn't make any progress or update about the issue @astrojuanlu

**Comment by astrojuanlu** [comment]
Hi @CosmicTiger, sorry for the long delay! I acknowledge that Hacktoberfest is over (at least until next year) but, for you and future readers: no need to ask for permission, feel free to open a pull request.

**Comment by Yash-10** [comment]
Hello, I am currently working on this issue. Will get back to you for discussion or with a PR soon.

Thank you!

**Comment by astrojuanlu** [comment]
Closed in gh-1056
