### ISSUE TITLE
Explore the use of RST substitutions or shortcuts

### ISSUE THREAD

**Issue by astrojuanlu** [poliastro/poliastro#1043]
https://github.com/astropy/astropy/issues/11063

Perhaps we could use for `poliastro.twobody.orbit.Orbit` and other classes that are referenced many times throughout the codebase.

**Comment by DhruvSondhi** [comment]
Hello, 
I was trying to work on this issue & this is the progress that I want to share, discuss & implement if tangible :
- I had checked out the main discussion from [this](https://github.com/astropy/astropy/issues/11063#issue-746991111) issue & have checked out [`rst_epilog`](https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-rst_epilog) & [`rst_prolog`](https://www.sphinx-doc.org/en/master/usage/configuration.html#confval-rst_prolog) for the same.
- After checking out the aforementioned discussion & documentation, I have implemented the same for example :
```python
rst_epilog = """

.. |Quantity| replace:: `~astropy.units.Quantity`

"""
```
- And for the same, I modified the `docstring` in `Cowell` function in `propagation.py` & the results are something of this sort :
![image](https://user-images.githubusercontent.com/66117751/105947398-0bd48900-608f-11eb-8f86-59f14364d3e8.png)
- This implementation makes the formatting of the class/method in question very different from others just as seen from the above screenshot. The links work as intended & also make it more obvious that this a class or function object in `docstring`.
-  I also tried implementing the same by removing the explicit replacement of `class` or `method` as from [this comment](https://github.com/astropy/astropy/issues/11063#issuecomment-732212333) after discussing with @astrojuanlu. The results for the same is as follows: { Though it doesn't work as expected, might be an implementation error 🤔 }  
![image](https://user-images.githubusercontent.com/66117751/105945985-5accef00-608c-11eb-90cc-a504ed5613c1.png)
This uses `.Quantity` instead of `|Quantity|`
- There is also another aspect as which needs to be taken into consideration that is the increased build time for building the docs.
> I'm trying to find how long the lookup takes. I recently timed my docs and docstrings with `` :class:`x` `` take a fair bit longer to compile than those without, and that's a direct link.
> But if they take similarly long, then perhaps direct substitutions are not necessary for classes as they are only 1 character shorter.

Quoted from [here](https://github.com/astropy/astropy/issues/11063#issuecomment-732262582).
- Now the question arises that do we need to implement the same? or can we tinker with the original implementation for repetitive part of the code in `docstring`?
- If we think to move forward with this implementation then I think `|Quantity|` is much better though it's formatting may be an issue of concern but the repetitive part of the code can be easily linked or referenced 😄

**Comment by DhruvSondhi** [comment]
@astrojuanlu Any update on the same?

**Comment by astrojuanlu** [comment]
This is how substitutions are treated in MyST: https://github.com/executablebooks/MyST-Parser/issues/190#issuecomment-747541869

Not sure if worth trying, I'm closing this issue for now.
