### ISSUE TITLE
Plotly plots on Google Colab?

### ISSUE THREAD

**Issue by astrojuanlu** [poliastro/poliastro#1238]
We got a user report that Plotly 3D plots do not show in Google Colab:

![colab](https://user-images.githubusercontent.com/316517/120122243-f049ce00-c1a7-11eb-8695-7ad7c24d62c3.png)

Can anybody confirm?

**Comment by Yash-10** [comment]
Hi,

When I run it on google colab, I get the 3D plot rendered:

![plotly](https://user-images.githubusercontent.com/68844397/120138527-46446300-c1f4-11eb-8da8-af6ad8bfeb97.png)

`poliastro==0.16.dev0` was used and it gives an (expected) error for `poliastro==0.15` (due to some recent changes in `astroquery` for `sbdb`)

Maybe either of the below could provide a fix?

- Changing the default renderer to `colab` using

```py
import plotly.io as pio
pio.renderers.default = 'colab`
```

For analysis, when I tried to change my default renderer to `notebook`, for example using

```py
import plotly.io as pio
pio.renderers.default = 'notebook`
```

I don't get any output. So maybe it has to do with the renderer?

- The `plotly` version (the above plot was using `plotly==4.4.1`). So if an older `plotly` version is installed, I think it might be a good choice to upgrade to the latest version?

---
Aside: I do get a warning after plotting (as seen in the screenshot) but I think it might be solved using:
```
pip install --upgrade tbb
```

Thanks!

**Comment by astrojuanlu** [comment]
Thanks @Yash-10 ! I'll wait a few days to the original user to clarify the status, otherwise I'll close the issue.

**Comment by astrojuanlu** [comment]
I confirm this solved the problem!

**Comment by JohaMR** [comment]
Hi, I have a question, how do I remove the axes and background grid on the chart?

**Comment by Yash-10** [comment]
Hi, I tried to use this:

```py
fig = frame.plot(ceres, label="510466")
fig.update_xaxes(showgrid=False, zeroline=False)
fig.update_yaxes(showgrid=False, zeroline=False)
fig.show()
```

but I wasn't able to get it to work. It may be because while I save `frame.plot(...)` to `fig`, the figure already gets plotted and changing the parameters afterwards doesn't have any effect. 

Maybe there should be an option internally in `poliastro` that allows setting axis on or off?

**Comment by astrojuanlu** [comment]
Hmm weird, I'll give it a shot myself. But I think @Yash-10 should be correct

**Comment by JohaMR** [comment]
Effectively the code doesn´t work @Yash-10

**Comment by astrojuanlu** [comment]
It's not a complete solution, but it's a start:

```python
plotter = OrbitPlotter3D()
fig = plotter.plot(ceres)
fig.update_layout(dict(scene=dict(
    xaxis=dict(showgrid=False, zeroline=False),
    yaxis=dict(showgrid=False, zeroline=False),
    zaxis=dict(showgrid=False, zeroline=False),
)))
```

The figure _can_ be updated with the correct methods, however I don't yet 100 % understand Plotly object model, so I would need some time to do this.

In any case, _somehow_ it should be possible.

**Comment by JohaMR** [comment]
Hi, I have another question, I am trying to construct the orbit from the orbital elements, I am working with astronomical units and degrees and I am getting the following error:

![image](https://user-images.githubusercontent.com/84646578/121723855-acf73580-caac-11eb-8d03-d03796106062.png)

Thanks  for the help :)

**Comment by Yash-10** [comment]
Hello @JohaMR , from the error, the arguments expect astropy's `Quantity` object. So if you would do this, for example,

```python
import astropy.units as u
a = 1.97608 * u.km
inc = 22.375820 * u.deg
...
```
(by passing in the appropriate units for each) and then pass these arguments to `Orbit.from_classical`, it would solve the error.

Thanks!

**Comment by JohaMR** [comment]
@Yash-10 Specify the units but look what I get now

![image](https://user-images.githubusercontent.com/84646578/121742858-07e95680-cac6-11eb-9a2c-e11bca72ec20.png)

**Comment by Yash-10** [comment]
Sorry I forgot to tell it earlier, but I think the eccentricity of an orbit is unitless by definition? It would be good to just pass it as a `float`. Does it help?

**Comment by JohaMR** [comment]
@Yash-10  thanks for your help!

**Comment by JohaMR** [comment]
I managed to change the background color of the graph, I don't know if @Yash-10 you know how to change the scale of the axes and you can help me.

Thanks :)

![image](https://user-images.githubusercontent.com/84646578/121784520-e2b62000-cb79-11eb-8f06-888513957e32.png)
![image](https://user-images.githubusercontent.com/84646578/121784525-eba6f180-cb79-11eb-9513-f499b9cb7c9e.png)
