### ISSUE TITLE
Absolute vs relative imports in modules

### ISSUE THREAD

**Issue by Yash-10** [poliastro/poliastro#1259]
There seem to be some places where the imports are done in a relative fashion whereas in an absolute sense at other places. For example, imports are relative [here](https://github.com/poliastro/poliastro/blob/main/src/poliastro/twobody/mean_elements.py) and absolute [here](https://github.com/poliastro/poliastro/blob/main/src/poliastro/twobody/elements.py)

From my preliminary understanding, relative imports are discouraged for intra-package imports since the modules might change locations during development but sometimes look good if the absolute import gets too long to write. 

So, the question is whether it would be good to:

- Convert all instances of relative imports to absolute, or
- Keep the imports as they are now, since they were kept (as they are) for some reason.

Would love to get any thoughts anyone might have!

Thanks!

**Comment by jorgepiloto** [comment]
Just to made public what it was discussed during the weekly community meeting on June the 25th, I agree with @Yash-10  about the usage of absolute imports over relative ones. However, we do not know if there is any advantage of using relative ones. Therefore, pinging @astrojuanlu here so he can give more information and suggestions on the topic 👍🏽

**Comment by astrojuanlu** [comment]
Hi folks, sorry for the long delay!

To my knowledge, there are no big advantages of relative imports over absolute ones. I think I switched to them because:

- It gives a clear visual distinction between dependencies and our own code
- It makes imports shorter

However, @Yash-10 is right that it is not consistent at the moment.

PEP 8 softly recommends absolute imports rather than relative imports, but "explicit relative imports are an acceptable alternative to absolute imports, especially when dealing with complex package layouts where using absolute imports would be unnecessarily verbose".

I would vote +1 on keeping them relative, but it's 2 to 1 now, so as you prefer :)

**Comment by Yash-10** [comment]
Thanks @astrojuanlu! From your suggestion, maybe we could keep the imports unchanged, keeping readability in mind.

**Comment by astrojuanlu** [comment]
I'd vote on consistency though, so either let's have them all relative or all absolute 👍🏽
