### ISSUE TITLE
Orbit position vectors and the `terminal` attribute of events

### ISSUE THREAD

**Issue by Yash-10** [poliastro/poliastro#1285]
I was experimenting with the added event detectors to create a "how-to" guide, where I found, probably, something strange:

**Expected behavior**

If the `terminal` attribute is set to False, the orbit position vectors must keep on propagating until `tofs[-1]` even if an event is triggered in between.

**Actual behaviour**

Orbit vectors get stuck if an event is triggered even if the `terminal` attribute of events is set to `False`.

**Reproducible example**
```py
import numpy as np

from poliastro.bodies import Earth

from poliastro.twobody.events import LatitudeCrossEvent
from poliastro.twobody.propagation import cowell
from poliastro.twobody.orbit import Orbit

r = [-6142438.668, 3492467.56, -25767.257] << u.km
v = [505.848, 942.781, 7435.922] << u.km / u.s
orbit = Orbit.from_vectors(Earth, r, v)

thresh_lat = 60 * u.deg
latitude_cross_event = LatitudeCrossEvent(orbit, thresh_lat, terminal=False)
events = [latitude_cross_event]

tofs = [1000, 1250, 1500, 1710, 2000] << u.s
rr, _ = cowell(
    Earth.k,
    orbit.r,
    orbit.v,
    tofs,
    events=events,
)
print(f"The threshold latitude was crossed {latitude_cross_event.last_t} s after the orbit's epoch")

print(rr)
```

gives output:

```
The threshold latitude was crossed 1701.7168421304814 s s after the orbit's epoch
[[-5636590.6652444   4435248.55827388  7410154.74204886]
 [-5510128.66403839  4670943.80747798  9269135.24138821]
 [-5383666.66274741  4906639.05661024 11128115.74058572]
 [-5281628.60050468  5096813.86201176 12628066.44401966]
 [-5281628.60050468  5096813.86201176 12628066.44401966]] km
```

The last two position vectors (corresponding to the time instants after the event was detected) are unexpectedly the same even if the `terminal` attribute was set to `False`.

**Possible ideas/solutions**

I think [this](https://github.com/poliastro/poliastro/blob/main/src/poliastro/twobody/propagation.py#L112) condition:

```py
if t_end is not None and t > t_end:
    t = t_end
```
checks if the current `t` instant is greater than the time instance of the event. If it is, then the t instance is brought back to the event instance time. This might be the cause of the above "unexpected" behavior. Interestingly, if I remove the lines:

```py
if t_end is not None and t > t_end:
    t = t_end
```
inside the `cowell` propagator, the events and propagation work as expected for the `terminal=False` case.

```

The threshold latitude was crossed 1701.7168421304814 s s after the orbit's epoch
[[-5636590.6652444   4435248.55827388  7410154.74204886]
 [-5510128.66403839  4670943.80747798  9269135.24138821]
 [-5383666.66274741  4906639.05661024 11128115.74058572]
 [-5277438.58161751  5104623.06584018 12689659.35981944]
 [-5130742.66000999  5378029.55473098 14846076.73864681]] km
```
(The last two position vectors now change)

Any suggestions on this would be helpful. Thanks!

**Comment by Yash-10** [comment]
One solution that I thought of:

```py
...
...
for i in range(len(tofs)):
    t = tofs[i]
    if t_end is not None and t > t_end:
        # Check if any event as terminal set to True, if yes,
        # then terminate propagation for all events,
        # irrespective of whether that event had terminal set to False.
        if any(event.terminal for event in events):
            t = t_end
    y = result.sol(t)
    rrs.append(y[:3])
    vvs.append(y[3:])
...
```
However, this assumes if any one event has `terminal` set to True, then terminate orbit propagation.

**Comment by jorgepiloto** [comment]
Thanks for noticing this @Yash-10!

So, it looks like the propagation properly stops but the dimension of the array of position vectors matches the one of the time of flight. This is probably because of the way scipy manages the integration process.

However, from my point of view, I think it is not useful at all to return a position/velocity array with non-changing values if the `terminal` parameter is set to `True`. Therefore, we should crop the output vectors just before they start repeating values. What do you think about this?

In addition to previous scenario, suppose we have a set of events such that:

```python
events_list = [event01, event02, event03]
```

where the first two are terminal ones but the last one is not. Let us assume that both `event01` and `event02` are triggered but one of them happens first. Propagation will take place up to a particular instant of time but there is no way for user to check which of those two first events happened in the first place. 

I think we can discuss all this in today's meeting and left the comments below so other people is aware about the final decision on how to address this.

**Comment by astrojuanlu** [comment]
- I agree with cropping the result vectors if the propagation is interrupted
- We will stop the propagation as soon as 1 terminal event triggers
- We decided to use the `last_t` property of the event to check which one was triggered

**Comment by astrojuanlu** [comment]
Was this closed in #1288 @Yash-10 ?

**Comment by Yash-10** [comment]
Yeah, it seems #1288 added the cropping condition proposed in this issue. So maybe a good time to close this? :)

**Comment by astrojuanlu** [comment]
Awesome 🚀
