### ISSUE TITLE
Converting `assert` statements to separate unit tests?

### ISSUE THREAD

**Issue by Yash-10** [poliastro/poliastro#1294]
`grep -r src/ -e assert` gives:

```
src/poliastro/frames/fixed.py:            assert type(equatorial_frame) == HCRS
src/poliastro/frames/fixed.py:            assert fixed_coo.body == equatorial_frame.body
src/poliastro/frames/fixed.py:            assert type(equatorial_coo) == HCRS
src/poliastro/frames/fixed.py:            assert equatorial_coo.body == fixed_frame.body
src/poliastro/twobody/propagation.py:    assert np.abs(f * gdot - fdot * g - 1) < 1e-5  # Fixed tolerance
src/poliastro/twobody/orbit.py:        assert np.any(r.value), "Position vector must be non zero"
src/poliastro/core/propagation/farnocchia.py:    assert abs(x) < 1
src/poliastro/core/propagation/farnocchia.py:    assert abs(x) < 1
src/poliastro/core/propagation/farnocchia.py:    assert abs(x) < 1
src/poliastro/core/propagation/farnocchia.py:    assert abs(x) < 1
src/poliastro/core/propagation/farnocchia.py:    assert abs(x) < 1
src/poliastro/core/propagation/farnocchia.py:    assert -np.pi <= nu < np.pi
src/poliastro/core/iod.py:    assert tof > 0
src/poliastro/core/iod.py:    assert k > 0
src/poliastro/core/iod.py:    assert abs(ll) < 1
src/poliastro/core/iod.py:    assert T > 0  # Mistake on original paper
```

Would it be a good choice to remove the above assert statements and instead convert them into their own unit tests?

For example, I had tried to perform a lambert maneuver where the final orbit's epoch was before the initial orbit's epoch where:

```
src/poliastro/core/iod.py:    assert tof > 0
```
was violated. I got an `AssertionError` with no error message. So maybe in such situations, it would be good to explicitly throw an error message? Also, would there be any reason to keep assert statements in `src` sometimes?

Thanks!

**Comment by astrojuanlu** [comment]
Yeah, good point @Yash-10. `assert` in the code is a lazy error handling mechanism, and a bad one. If the assert is `False`, an error without message is raised.

At the same time, some of those assertions could just go away, since the code is supposed to give that result. Therefore, we would need some judgement to understand which `assert` statements to remove, and which ones to transform into a `try ... except` block.

One idea:

- Replace all `assert` statements in `poliastro.core` with `assert cond, msg` (so at least the assertion gives a message if it's false)
- Replace all remaining `assert` statements by an appropriate `try ... except` block

What do you think?
