### ISSUE TITLE
Drop Codeclimate

### ISSUE THREAD

**Issue by astrojuanlu** [poliastro/poliastro#1316]
We barely pay any attention to Codeclimate, its warnings are a distraction, and more often than not we choose to ignore it. This is a burden, but especially so for new contributors, that think that they have to address Codeclimate warnings.

Should we

a) Just drop it, or
b) Tune the settings so it's more fit for our needs, and committing to follow it?

I vote (a)

**Comment by jorgepiloto** [comment]
Yeah, those warnings on non-tested lines of code are quite annoying when reviewing PR... I think the tools we currently use such already perform most of the tasks Codeclimate does. Voting for option "(a)" too 🖐🏽

**Comment by Yash-10** [comment]
As both of you say, it will be good to drop Codeclimate. I had also observed that since PRs get merged despite Codeclimate complaining about, say, no. of arguments to a method, it sometimes raises an error in new PRs that didn't change the line which it was complaining about earlier. For consistency, maybe a good choice to drop it.

**Comment by astrojuanlu** [comment]
Renamed issue, and relabeled it as good first issue.

**Comment by Syed-Osama-Hussain** [comment]
I think removing codeclimate.yml should do the job as I don't see any other references to it, right?

**Comment by astrojuanlu** [comment]
Correct @Syed-Osama-Hussain !
