### ISSUE TITLE
Errors during the testing process

### ISSUE THREAD

**Issue by frantseva** [poliastro/poliastro#133]
Good day! 
I successfully installed poliastro on Mac with OS X El Capitan Version 10.11.6.
During the testing process 3 errors and 1 failure appeared. 

ERROR collecting tests/test_ephem.py
ERROR collecting tests/test_hyper.py 
ERROR collecting tests/test_iod.py

===== FAILURES 
___test_body_printing_has_name_and_symbol  
(more info is in attached file)
Can you suggest something, please?

[errors.txt](https://github.com/poliastro/poliastro/files/428531/errors.txt)

**Comment by Juanlu001** [comment]
Hi, thanks for trying poliastro out! I think the errors might be related to
the use of Python 2, do you have the chance to upgrade? Otherwise I would
suggest you downloading poliastro 0.4.2, which is the latest version
supporting Python 2.

What are you considering poliastro for by the way? I'm collecting some
success stories for the package so if you have any feature requests or
suggestions just open an issue or write me an email!

On 21 Aug 2016 00:14, "frantseva" <notifications@github.com> wrote:

Good day!
I successfully installed poliastro on Mac with OS X El Capitan Version
10.11.6.
During the testing process 3 errors and 1 failure appeared.

ERROR collecting tests/test_ephem.py
ERROR collecting tests/test_hyper.py
ERROR collecting tests/test_iod.py

===== FAILURES
___test_body_printing_has_name_and_symbol

(more info is in attached file)
Can you suggest something, please?

errors.txt <https://github.com/poliastro/poliastro/files/428531/errors.txt>

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/poliastro/poliastro/issues/133>, or mute the thread

**Comment by frantseva** [comment]
Hi again!
So far I decided to use older version 0.4.0
All the tests passed successfully! Thanks! 

I'm using Poliastro as a converting tool for orbital elements. Very convenient!

**Comment by Juanlu001** [comment]
Cool! Let's close the issue then, feel free to open new ones if problems arise.

**Comment by frantseva** [comment]
Hi! Is this correct email address juanlu@pybonacci.org ?

**Comment by Juanlu001** [comment]
It's correct, but I won't have access to it for a few days. Would you write me to the address that appears [here](https://github.com/poliastro/poliastro/commit/643ba1ff.patch)?
