### ISSUE TITLE
Separate `dev` from `doc` dependencies

### ISSUE THREAD

**Issue by astrojuanlu** [poliastro/poliastro#1407]
This list of `dev` dependencies is too long:

https://github.com/poliastro/poliastro/blob/1b3da82d82328c5d748959455d93b18b1e740364/pyproject.toml#L70-L98

Found while discussing https://github.com/numba/numba-integration-testing/pull/77

**Comment by tjnd89** [comment]
In order to get the docs to build with "make html" I had to install the following dependencies (after following the contributing instructions to build my virtualenv.

sphinx 
sphinx-rtd-theme 
sphinx-autoapi 
nbsphinx 
sphinx_gallery 
IPython 
sphinx_copybutton 
sphinx-notfound-page
sphinx-hoverxref
myst_parser
jupytext
ipykernel
czml3

This might help with splitting out the doc dependencies.

**Comment by astrojuanlu** [comment]
Thanks a lot @tjnd89 ! Looks like I opened this issue right on time
