### ISSUE TITLE
autoapi.extension and sphinx.ext.autodoc together?

### ISSUE THREAD

**Issue by Codeberg-AsGithubAlternative-buhtz** [poliastro/poliastro#1489]
You use `autoapi.extension` and `sphinx.ext.autodoc` as sphinx extensions together.

https://github.com/poliastro/poliastro/blob/38a28e4713986df9098e8948935c5b63e9f1b115/docs/source/conf.py#L22-L24

In my understanding this two extensions are concurring against each other. I would like to understand why you use them together and what the benefits are.

Thanks in advance

**Comment by astrojuanlu** [comment]
Hi @Codeberg-AsGithubAlternative-buhtz! It's a good question, maybe it's a relic from some older configuration. Have you tried building the docs without `sphinx.ext.autodoc`?

**Comment by Codeberg-AsGithubAlternative-buhtz** [comment]
No I have not.

**Comment by astrojuanlu** [comment]
We primarily use autoapi

**Comment by astrojuanlu** [comment]
Okay, it's a bit embarrasing that I gave such a bad answer, but in my defense I was ramping up a new job and I was extremely busy.

We use [autodoc-style directives](https://sphinx-autoapi.readthedocs.io/en/latest/reference/directives.html#autodoc-style-directives) in some places, and that's why we need both.

> These directives work similarly to autodoc, but docstrings are retrieved through static analysis instead of through imports.
> To use these directives you will need to enable the autodoc extension in your Sphinx project’s conf.py:
> `extensions = ['sphinx.ext.autodoc', 'autoapi.extension']`

See for example:

https://github.com/poliastro/poliastro/blob/3abced1b27ee7a9ac9ae51b2bdf4723b1c3239e4/docs/source/api.md?plain=1#L21-L34

Feel free to open another issue or drop us a message in the chat if you have any further questions.
