### ISSUE TITLE
build_ephem_interpolant error for short propagation timespan

### ISSUE THREAD

**Issue by atergt** [poliastro/poliastro#1494]
🐞 Hi, I am using the `poliastro.core.perturbations.third_body` module to define the third body perturbation of the moon on satellites orbit. I defined a function that takes into account that perturbation together with the others that can be defined with poliastro. The function seems to work for propagation times longer than 15 days, however, it gives me problems for shorter propagation periods (I need to propagate for less than a day).
I tried reducing the timestep but the error persists. Do you have any idea what could be the reason for it and how can I try to fix it?

This is the function I created, and the example inputs I put.
Note that the same script works, setting tofs = 28 * u.day and ts = 600 * u.s

```python
# %% Import packages and modules

import numpy as np

from astropy.coordinates import solar_system_ephemeris
from astropy.time import Time, TimeDelta
from astropy import units as u

from poliastro.bodies import Earth, Moon, Sun
from poliastro.constants import rho0_earth, H0_earth
from poliastro.constants.general import Wdivc_sun

from poliastro.core.elements import rv2coe
from poliastro.core.perturbations import atmospheric_drag_exponential, third_body, J2_perturbation, radiation_pressure
from poliastro.core.propagation import func_twobody

from poliastro.ephem import build_ephem_interpolant
from poliastro.twobody import Orbit
from poliastro.twobody.propagation import propagate, cowell


# %% Functions definition

def perturbed_propagator(attractor, orbit, time_of_flight, time_step, C_D, A_over_m, C_R, As_over_m):
    """
    Propagates orbit in time using Cowell's method, considering perturbations from atmospheric drag, oblateness, solar
    radiation pressure and Moon's gravity.

    Parameters
    ----------
    attractor : Body
        Main attractor of the orbit.
    orbit : Orbit
        Initial orbit.
    time_of_flight : ~astropy.units.Quantity
        Duration of propagation (day).
    time_step : ~astropy.units.Quantity
        Time step between measurements (s).
    C_D: float
        Dimensionless drag coefficient ().
    A_over_m: ~astropy.units.Quantity
        Frontal area/mass of the spacecraft (km^2/kg).
    C_R: float
        Dimensionless radiation pressure coefficient, 1 < C_R < 2 ().
    As_over_m: ~astropy.units.Quantity
        Effective spacecraft area/mass of the spacecraft (km^2/kg).

    Returns
    ----------
    orb_f, orb_elem, state_f :
        Final orbit (orb_f), Time variation of the classical orbital parameters [a (km), ecc (), inc (deg), raan (deg),
        argp (deg), nu (deg)] (orb_elem), Time variation of the state vector [x (km), y (km), z (km), vx (km/s),
        vy (km/s), vz (km/s)] (state_f).
    """

    # Attractor's parameters

    k = attractor.k.to(u.km ** 3 / u.s ** 2).value
    J2 = attractor.J2
    R = attractor.R.to(u.km)
    rho0 = rho0_earth.to(u.kg / u.km ** 3)  # Earth's atmosphere density at sea level
    H0 = H0_earth.to(u.km)  # scale height [km]

    # Solar System ephemerides (different databases can be used)

    # solar_system_ephemeris.set('builtin')  # uses PyERFA routines
    # solar_system_ephemeris.set('de430')  # uses default JPL ephemerides (from 1550 to 2650)
    solar_system_ephemeris.set("de432s")  # uses reduced JPL ephemerides (from 1950 to 2050)

    # Starting epoch

    epoch0 = orbit.epoch
    epoch0.format = 'jd'

    # Time of flight definition

    p_s = time_of_flight.to(u.s)  # propagation period in seconds
    time_step = time_step.to(u.s)  # time step to propagate
    tofs = TimeDelta(np.arange(0, p_s.value + 1.0, time_step.value) * u.s)
    p_day = p_s.to(u.day)

    # Third body parameters (Moon)

    moon_period = 28 * u.day  # Moon's orbital period (w.r.t. Earth)
    moon_3b = build_ephem_interpolant(
        Moon, moon_period, (epoch0.value * u.day, epoch0.value * u.day + p_day), rtol=1e-2
    )
    moon_k = Moon.k.to(u.km ** 3 / u.s ** 2).value  # Moon's gravitational parameter [km3/s2]

    # Sun parameters

    sun_period = 365 * u.day  # Sun's orbital period (w.r.t. Earth)
    sun_srp = build_ephem_interpolant(
        Sun, sun_period, (epoch0.value * u.day, epoch0.value * u.day + p_day), rtol=1e-2
    )

    def a_pert(t0, state, k, J2, R, C_D, A_over_m, H0, rho0, k_third, perturbation_body, C_R, As_over_m, Wdvic_s, star):
        return J2_perturbation(t0, state, k, J2, R) \
               + atmospheric_drag_exponential(t0, state, k, R, C_D, A_over_m, H0, rho0) \
               + third_body(t0, state, k, k_third, perturbation_body) \
               + radiation_pressure(t0, state, k, R, C_R, As_over_m, Wdvic_s, star)

    def f_pert(t0, state, k):
        du_kep = func_twobody(t0, state, k)
        ax, ay, az = a_pert(
            t0,
            state,
            k,
            J2=J2.value,
            R=R.value,
            C_D=C_D,
            A_over_m=A_over_m.value,
            H0=H0.value,
            rho0=rho0.value,
            k_third=moon_k,
            perturbation_body=moon_3b,
            C_R=C_R,
            As_over_m=As_over_m.value,
            Wdvic_s=Wdivc_sun.value,
            star=sun_srp,
        )
        du_ad = np.array([0, 0, 0, ax, ay, az])
        return du_kep + du_ad

    coords = propagate(
        orbit,
        tofs,
        method=cowell,
        f=f_pert,
    )

    rr = coords.xyz.T.to(u.km).value
    vv = coords.differentials["s"].d_xyz.T.to(u.km / u.s).value
    state_f = np.concatenate([rr, vv], axis=1)

    p = np.array([[rv2coe(k, r, v)[0] for r, v in zip(rr, vv)]]).T
    ecc = np.array([[rv2coe(k, r, v)[1] for r, v in zip(rr, vv)]]).T
    inc = np.array([np.rad2deg([rv2coe(k, r, v)[2] for r, v in zip(rr, vv)])]).T
    raan = np.array([np.rad2deg([rv2coe(k, r, v)[3] for r, v in zip(rr, vv)])]).T
    argp = np.array([np.rad2deg([rv2coe(k, r, v)[4] for r, v in zip(rr, vv)])]).T
    nu = np.array([np.rad2deg([rv2coe(k, r, v)[5] for r, v in zip(rr, vv)])]).T
    a = np.array([[rv2coe(k, r, v)[0] / (1.0 - rv2coe(k, r, v)[1] ** 2) for r, v in zip(rr, vv)]]).T

    orb_elem = np.concatenate([a, ecc, inc, raan, argp, nu], axis=1)

    orb_f = orbit.propagate(
        tofs[-1],
        method=cowell,
        f=f_pert,
    )

    return orb_f, orb_elem, state_f

# %%
epoch0 = Time(
    '2000-01-01 12:00:00.000', format='iso', scale='tdb'
)
epoch0.format = 'jd'

# Initial classical orbital parameters

a0 = 6978.137 * u.km  # initial semi-major axis [km]
ecc0 = 0.00000001 * u.one  # initial eccentricity [/]
inc0 = 97.906 * u.deg  # initial inclination [deg]
raan0 = 140.819 * u.deg  # initial RAAN [deg]
argp0 = 0 * u.deg  # initial argument of perigee [deg]
nu0 = 167.299 * u.deg  # initial true anomaly [deg]

# Initial orbit in the Geocentric Celestial Reference System (GCRS) frame

orb0 = Orbit.from_classical(Earth, a0, ecc0, inc0, raan0, argp0, nu0, epoch0)

tofs = 0.5 * u.day
ts = 1 * u.s

# %% Customizable parameters definition

# Satellite properties

C_D = 2.2  # drag coefficient
m = 100 * u.kg  # mass [kg]
A = np.pi / 4.0 * (u.m ** 2)  # cross-sectional area (atmospheric drag) [m2]
As = A  # absorbing area (solar radiation pressure) [m2]
A_over_m = (A / m).to(u.km ** 2 / u.kg)  # effective area-to-mass ratio [km2/kg]
As_over_m = (As / m).to(u.km ** 2 / u.kg)  # absorbing-area-to-mass ratio [km2/kg]
B = C_D * A_over_m  # ballistic coefficient [km2/kg]
C_R = 2

# %%
orb_f, orb_elem, state_f = perturbed_propagator(Earth, orb0, tofs, ts, C_D, A_over_m, C_R, As_over_m)
```

TRACEBACK:

```
Traceback (most recent call last):
  File "C:\Users\user\PycharmProjects\pythonProject2\main.py", line 190, in <module>
    orb_f, orb_elem, state_f = perturbed_propagator(Earth, orb0, tofs, ts, C_D, A_over_m, C_R, As_over_m)
  File "C:\Users\user\PycharmProjects\pythonProject2\main.py", line 85, in perturbed_propagator
    moon_3b = build_ephem_interpolant(
  File "C:\Users\user\anaconda3\envs\pythonProject2\lib\site-packages\poliastro\ephem.py", line 76, in build_ephem_interpolant
    return interp1d(t_values, r_values, kind="cubic", axis=0, assume_sorted=True)
  File "C:\Users\user\anaconda3\envs\pythonProject2\lib\site-packages\scipy\interpolate\_interpolate.py", line 564, in __init__
    self._spline = make_interp_spline(xx, yy, k=order,
  File "C:\Users\user\anaconda3\envs\pythonProject2\lib\site-packages\scipy\interpolate\_bsplines.py", line 1326, in make_interp_spline
    raise ValueError("The number of derivatives at boundaries does not "
ValueError: The number of derivatives at boundaries does not match: expected 3, got 0+0
```

**Comment by astrojuanlu** [comment]
Hi @atergt , thanks for opening the issue. It looks like there are some formatting issues with your code, I'll do my best to edit it myself.

This looks like a genuine bug, we'll look into it.

**Comment by applysomesky** [comment]
Got this script working. 

Not sure if in the meantime the main problem was already fixed but I think so, since I get another error:
```
File "C:\...\poliastro\src\poliastro\ephem.py", line 58, in build_ephem_interpolant
    interpolant = interp1d(
File "C:\...\poliastro\lib\site-packages\scipy\interpolate\interpolate.py", line 561, in __init__
    raise ValueError("x and y arrays must have at "
ValueError: x and y arrays must have at least 2 entries
```

To root of the remaining problem is in setting `rtol=1e-2` for `build_ephem_interpolant`, which is in default set to `1e-5`. 

https://github.com/poliastro/poliastro/blob/8df4f0698c9ccb529b457522127295462ecc957f/src/poliastro/ephem.py#L49-L55

In the script above `t_span[1] - t_span[0]` equals `0.5 u.day`, `period = 28 u.day`, with `rtol=1e-2` this leads to `periods = int(0.5/0.28) = 1`, resulting in the single number `0`, which is not a time range. Using the default of `rtol = 1e-5` causes no problems since it leads to 1785 timesteps instead of 0.

In my humble opinion I think the keyword `periods` is a bit of a confusing name, `steps` or `time_steps` would be more suitable.

After that we get the propagator error message:
```
ImportError: The 'propagate' function is gone, use either Orbit.propagate if you want to retrieve the final state, or Orbit.to_ephem if you want to compute all the trajectory. This error message will be removed in a future release and you will get a 'ImportError: cannot import name 'propagate' from 'poliastro.twobody.propagation''.
```

Importing the needed functions, removing the `state_f` for now, and doing the propagation as follows makes sure the script runs:
```
rr, vv = orbit.to_ephem(EpochsArray(orbit.epoch + tofs, method=CowellPropagator(f=f_pert))).rv()
```

**Comment by applysomesky** [comment]
I now see something similar happened in #1506.

**Comment by astrojuanlu** [comment]
> I now see something similar happened in https://github.com/poliastro/poliastro/issues/1506.

Right. I think it's time to amend this API. Probably we should get rid of `periods` and `rtol` altogether and just use whatever `time_range` accepts? Or even let the user choose the epochs from the outside using `poliastro.util.time_range` and then have `build_ephem_interpolant` receive the epochs directly.

> Importing the needed functions, removing the state_f for now, and doing the propagation as follows makes sure the script runs:
> ```
> rr, vv = orbit.to_ephem(EpochsArray(orbit.epoch + tofs, method=CowellPropagator(f=f_pert))).rv()
> ```

👍🏽 I'm glad the error message I wrote was useful 🙂

**Comment by applysomesky** [comment]
I was looking at what `build_ephem_interpolant` actually does. 

The only reason I can think of for using the current method (using `period` and `rtol`) is in case the user does not know how fast/slow the object is orbiting. Then again, setting `rtol = 1e-2` for Jupiter and Moon will in both cases yield 100 points if the `t_span` is chosen to be their orbital period. These 100 points are spaced very differently in time _and_  space. Alternatively, if I would like to do a satellite propagation using 3rd body perturbations I want the position of these 2 objects (Jupiter and Moon) at set points in time, being my simulation `t_span` divided by X points, such that the objects are at the most up-to-date position at time of simulating 3rd body perturbations for example (this becomes more difficult with variable stepsize integrators of course). Therefore the `period` and `rtol` method seems not very useful, but maybe I am not aware of other useful aspects of this method (would be worth checking the initial commit if it was always like the current method, or was changed to its current method for some reason).

Going over your suggestions:
1. I think your last solution using a `time_range` is very suitable since it will already show the user if the `time_range` turns out to be only 0 or 1 points in time. Then I still want to suggest to think about the `periods` argument naming in that function, `time_steps`/`steps`/`number_of_samples` could be used instead. Using `time_range` is handy if a user wants to make multiple ephem interpolants at the same time, he/she could reuse this time range.

2. If we want to give less control to the user, I would opt for keeping the `time_range` inside the `build_ephem_interpolant` function and remove `period` and `rtol` and replace it with either of `time_steps`/`steps`/`number_of_samples` instead, and use that directly in `periods` part of `time_range`:
https://github.com/poliastro/poliastro/blob/8df4f0698c9ccb529b457522127295462ecc957f/src/poliastro/ephem.py#L49-L56

**Comment by astrojuanlu** [comment]
I say let's go for your first option, and

1. accept an `epochs` parameter in `build_ephem_interpolant`. Taking the example of the original issue, instead of

```python
    moon_3b = build_ephem_interpolant(
        Moon, moon_period, (epoch0.value * u.day, epoch0.value * u.day + p_day), rtol=1e-2
    )
```

the user would do

```python
    moon_3b = build_ephem_interpolant(
        Moon, time_range(epoch0, end=epoch0.value * u.day + p_day),
    )
```

2. rename `periods` in `time_range` to `num_values` (to match what the sampling strategies do)

Then the user can play with either `num_values` or `spacing` to achieve the accuracy they want.
