### ISSUE TITLE
small errata in orbit from classical elements documentation

### ISSUE THREAD

**Issue by AunSiro** [poliastro/poliastro#154]
There is a small erratum in the definition of the parameters in the function that generates an orbit from classical elements, in orbit.py  line 64. It states:
> p : Quantity
> Semilatus rectum.

But it should be:

> a : Quantity
> Semi-major axis.

This small mistake is also present at the documentation page: http://poliastro.readthedocs.io/en/latest/api.html#poliastro.twobody.Orbit.from_classical

If you wish, I can correct the method in orbit.py with the next commit at #153 , but I don't know how to change the documentation page.

**Comment by Juanlu001** [comment]
Oops! This is probably due to the dozen times I switched from one to the
other...

Anyway #153 is not related to that module so I'd rather fix it separately.
I will do that myself so the CI do not run. Thanks!

On 11 Mar 2017 01:05, "Siro" <notifications@github.com> wrote:

There is a small erratum in the definition of the parameters in the
function that generates an orbit from classical elements, in orbit.py line
64. It states:

p : Quantity
Semilatus rectum.

But it should be:

a : Quantity
Semi-major axis.

This small mistake is also present at the documentation page:
http://poliastro.readthedocs.io/en/latest/api.html#
poliastro.twobody.Orbit.from_classical

If you wish, I can correct the method in orbit.py with the next commit at
#153 <https://github.com/poliastro/poliastro/pull/153> , but I don't know
how to change the documentation page.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/poliastro/poliastro/issues/154>, or mute the thread

**Comment by Juanlu001** [comment]
Closed by #177.
