### ISSUE TITLE
Split and optimize the libraries to make Poliastro lighter

### ISSUE THREAD

**Issue by meristian** [poliastro/poliastro#168]
In function of make Poliastro lighter I open this issue.

Optimize and rewrite the code of the library itself and their libraries (numpy , scipy , etc.) will be the goal of this Issue. We can learn much more about the libraries we use , know wich parameters and variables are wrongly used.

Watching how will coders apply this library , Poliastro , make it lighter to pave the way for mobile devices and , why not , videogames. Poliastro is useful to make plotters of spacial travels but also is the easyest way to make computation of pyshic parameters.

Speed up all the apps that will be done with this library is the main purpouse.

I will updating this issue with another ways to optimize our code.

**Comment by Juanlu001** [comment]
Thanks @Thextroyer for the idea! We can leave this as issue as a TODO item, but further information should go to the wiki as the proposal might be complex. If you intent to work on this for SOCIS, I will send the information to the mailing list very soon :)

**Comment by Juanlu001** [comment]
I'm removing the SOCIS label, but leaving the issue open in case anyone wants to work on it :)

**Comment by Juanlu001** [comment]
I am not sure whether the optimization should happen in poliastro itself, an alternative "simpler" implementation should be made or a server-client architecture using JavaScript/TypeScript should be explored. I'm marking this as a question for the future.

**Comment by Juanlu001** [comment]
@ZachDischner said in https://github.com/poliastro/poliastro/issues/156#issuecomment-413333078 that he was having problems to zip all poliastro dependencies to AWS Lambda:

> Lambda wants you to upload a zip of the whole environment to use during runtime. Poliastro dependencies make the zip too big for their size limits (and it is a pain in the butt to build libs for Amazon Linux). 

I think that's a pity because probably the biggest contributor to dependencies weight is SciPy, and we only use a couple of packages in it. Also, for a setting like this you probably could get away without Jupyter and choosing one plotting backend (either Plotly or matplotlib). I would like to put some effort here to make poliastro lighter. Perhaps something like the Dask devs do:

https://github.com/dask/dask/blob/e7a71c092def9d8d16580bfa3456e6b85334656b/setup.py#L10-L17

**Comment by Juanlu001** [comment]
I read that the limit for code uploaded to AWS Lambda is 250 MB https://hackernoon.com/exploring-the-aws-lambda-deployment-limits-9a8384b0bec3 @ZachDischner did all the poliastro dependencies weigh more than this, uncompressed?

**Comment by Juanlu001** [comment]
Another kind of platforms that would benefit from having a lighter poliastro are Raspberry Pi, Micropython... But for that we would have to bring back Python 3.4 support, which means working with Astropy < 3.

**Comment by ZachDischner** [comment]
My unzipped env size ended up being around 375 MB. I agree that a lightweight variant with few dependencies would be excellent. A lambda-ready minimal env like those provided here https://github.com/ryfeus/lambda-packs <https://github.com/ryfeus/lambda-packs> would make building serverless apps around poliastro a breeze (especially if Matplotlib was removed entirely in lieu of a more cloud-style plotting approach like plotly).

Another thing to think about though is the use of ephemeris files auto downloaded when needed. For light workloads, lambda would dump the container running poliastro and would have to re-download ephemeris files on every fresh call/container boot up. A minimal Poliastro with adequate ephemeris data included that required no net connection to start using would be great for Lambda as well as offline applications.

**Comment by Juanlu001** [comment]
Candidates for optional dependencies, also in light of #453:

* SciPy is used sparingly in poliastro, and there are ways to minimize our dependency on it:
  - #456 
  - It's not used in the basic (`mean_motion`) integrator anymore, since we wrote our own, fast Newton method
  - It's not used in `kepler` either, since the Kepler iteration is hardcoded
  - It's only required for the Cowell method
* jplephem is already an optional dependency of Astropy, and probably we should keep it as such, since the default ephemeris is good enough for an approximation (see also #445)
* matplotlib should be made less important in favor of Plotly, now that 2D and 3D backends are present, to increase consistency and favor dynamic, interactive workflows, whereas matplotlib can be kept for static plots (for reports and papers)
* plotly makes sense mostly for notebook workflows (#338) and jupyter is not currently a required dependency, so it should be made optional as well
* numba should be made optional again
* beautifulsoup4, requests and pandas are only used in the NEOS package, and it should be in astroquery anyway (#364)
  - astroquery could be made optional as well
  - pandas is only used for one function https://github.com/poliastro/poliastro/blob/a9a5a235e47b569542920df64b93879fab4f99b5/src/poliastro/neos/dastcom5.py#L540-L565 so it could be made optional as well

This way, the only core dependencies of poliastro would be numpy and astropy.

To make all these dependencies optional, we have to:

1. Work on **all** the issues listed above
2. Improve error messages for missing dependencies
3. Allow `pip install poliastro`/`pip install poliastro[complete]` and `conda install poliastro`/`conda install poliastro-core`, as it's done in Dask https://dask.pydata.org/en/latest/install.html
4. Improve installation documentation

**Comment by Juanlu001** [comment]
Taking care of `pip install poliastro[jupyter]` in #548 and removing my assignation from this more general issue.

**Comment by Juanlu001** [comment]
Removing the milestone.

**Comment by Juanlu001** [comment]
Note that beautifulsoup4, requests and pandas have been removed from the explicit list of dependencies, although we added astroquery instead:

https://github.com/poliastro/poliastro/blob/ea6a0eb34855af37267ca8df315652c9e03a3721/pyproject.toml#L34-L45

**Comment by astrojuanlu** [comment]
Given that the users of poliastro are not experts in Python packaging + that the original case for this is less and less important (apparently cloud environments allow larger and larger environments) + we closed #364 after realizing that sbdb was abandoned + that we are already considering splitting `poliastro.core` from the rest #1207, it's a good moment to reevaluate this issue.

Currently, the heaviest _direct_ dependencies are (sizes corresponding to `cp38-manylinux` or universal wheels):

- SciPy (~40 MB)
- numba + llvmlite (~30 MB)
- Plotly (~25 MB)
- pandas, astropy, matplotlib (~11 MB)

I think we should concentrate our efforts on these tasks, in order of increasing difficulty:

- Splitting `poliastro.core` as described in #1207 (this allows users to install only algorithms + numba, removes the rest of the heaviest dependencies, and opens the door to make an even more stripped down version, entirely without numba)
- Make plotting opt-out (as opposed to opt-in, to avoid alienating beginners) (this enables easier cloud deployments that will only export data to some text format).
- Remove dependency on SciPy (it carries too much, and we only use it for a couple of minor things, but we have to pay the full ticket anyway - this is the most difficult though, because it requires finding alternatives, or maintaining part of the code ourselves).

**Comment by astrojuanlu** [comment]
I had an idea: create a `poliastro._math` subpackage to group all our dependency with SciPy, so it is easier to refactor in the future. Already started doing it.

**Comment by astrojuanlu** [comment]
`poliastro._math` was added in https://github.com/poliastro/poliastro/pull/1434. I think adding too many layers of optional stuff might be too much work beyond gh-1207, so I'm closing this issue.
