### ISSUE TITLE
Prepare documentation for 0.9

### ISSUE THREAD

**Issue by Juanlu001** [poliastro/poliastro#344]
According to our plans, the proposed release date for poliastro 0.9 is April 20th:

https://github.com/poliastro/poliastro/milestone/9

(the remaining issues there are not important and can be moved to the next release)

@shreyasbapat @nikita-astronaut @ritiek You added new code to poliastro since 0.8.x:

https://github.com/poliastro/poliastro/compare/0.8.x...master

So make sure that:

* The corresponding functions show correctly in the API reference http://docs.poliastro.space/en/latest/api.html
* If relevant/important/if you care, some explanation is given in the User Guide http://docs.poliastro.space/en/latest/user_guide.html
* If really worth it, add a notebook that showcases the new functionality http://docs.poliastro.space/en/latest/jupyter.html properly indexed in https://github.com/poliastro/poliastro/blob/master/index.ipynb with a beautiful screenshot :wink: 

I only did bug fixing and some infrastructure changes, so I don't have much to add to the docs. I will prepare the release notes though, starting next Wednesday.

**Comment by shreyasbapat** [comment]
> If relevant/important/if you care, some explanation is given in the User Guide http://docs.poliastro.space/en/latest/user_guide.html

How to add points in this file?

**Comment by Juanlu001** [comment]
Apart from keeping the tone and structure of the document, I don't have
more specific advice :)

**Comment by shreyasbapat** [comment]
No! I am asking how to add more content to this page?

**Comment by ritiek** [comment]
API reference looks good enough to me for [`poliastro.twobody.orbit.Orbit.sample`](http://docs.poliastro.space/en/latest/api.html#poliastro.twobody.orbit.Orbit.sample) (#312). I personally don't think it is worth a jupyter notebook. However, I am willing to add one if you guys feel otherwise! 

@shreyasbapat I think it is this file [docs/source/user_guide.rst](https://github.com/poliastro/poliastro/blob/35a2c34e8e52bbb7ad7bff29e7c41eaf9c30c135/docs/source/user_guide.rst).
