### ISSUE TITLE
Multiple revolutions lambert solution

### ISSUE THREAD

**Issue by Tarlan0001** [poliastro/poliastro#496]
I'm using the `izzo.lambert` function to solve the lambert problem. Trying to implement the multirevolution solution, taking the transfer time from [1,100] days interval. I got
```
    for v0, v in sols:
ValueError: No feasible solution, try lower M
```

These are the vectors:
`r0=[-5396.060601014418, -2995.128313159499, -6223.416953125992] *u.km`
`r =[8916.202484966101, 18190.886121079544, 37797.86948723022] *u.km`

First orbit:
- apogee 8000
- perogee 600
- inc 64.3*math.pi/180
- raan 0
- aop 310*math.pi/180

Second orbit
- apogee 39000
- perigee 800
- inc 64.3*math.pi/180
- raan 0
- aop 270*math.pi/180

How could I use multi-revolution solution?

**Comment by Juanlu001** [comment]
Hi @Tarlan0001, sorry for the delay! In this case it's perfectly possible that there are no multi-revolution solutions for this particular case. You should check the maximum `M` that does _not_ give an error.

If you want to know more about the mathematical preconditions for a multi-revolution solution to exist, I recommend you this paper:

https://arxiv.org/pdf/1403.2705v2.pdf

This is not really a problem in poliastro, so with your permission I'm closing. Feel free to keep adding comments though!

**Comment by Tarlan0001** [comment]
Is it possible, using poliastro, to get a more optimal trajectory, than via `izzo.lambert(Earth_k, r0, r, tof, M=0)`?

**Comment by Juanlu001** [comment]
@Tarlan0001 Just looking at a quick plot, it seems that the two orbits intersect:
![newplot 1](https://user-images.githubusercontent.com/316517/48858054-b61f3a80-edba-11e8-8e74-9978dd0b4877.png)
Therefore, you shouldn't need to perform a Lambert maneuver, and it fact using `lambert` here is dragging you because you are forced to select a specific point in the orbit.

In this case, I would try to (either using pen and paper, or finding the two local minima of the function that gives the distance between the two orbits) find the orbit intersection points, and changing from one to the other should be _one finite burn_. As there seem to be two intersections, there will be one burn that should be cheaper than the other.

**Comment by Tarlan0001** [comment]
Are you sure?

Single burn requires more than 2km/s impulse (the intersection is at 330 and 10 true anomaly). 
However, lambert needs 1.5km/s (from 282 to 168 true anomaly in 270 minutes).

**Comment by Juanlu001** [comment]
Interesting. Can you share the code you are using to compute both costs? I guess you are sampling both orbits and computing the best pair for the Lambert transfer?

**Comment by Juanlu001** [comment]
I plotted your results and I just can conclude that you're right!

![index](https://user-images.githubusercontent.com/316517/48894915-2de57780-ee44-11e8-8bfe-e0b92dc9771e.png)

Several recommendations:

* You can use `from poliastro.util import norm` to compute the norm of vectors with units.
* Instead of your own `keplerian2cartesian`, you can do this:

```python
from poliastro.core.elements import coe2rv

Earth_k_val = Earth_k.decompose([u.m, u.s]).value

def keplerian2cartesian_alt(kepler):

    a=(kepler[0]+kepler[1]+Req*2)*1000/2  # m
    e=(kepler[0]-kepler[1])/(kepler[0]+kepler[1]+Req*2)
    i=kepler[2]
    OMEGA=kepler[3]
    omega=kepler[4]
    tetta=kepler[5]

    p = a * (1 - e ** 2)

    return coe2rv(Earth_k_val, p, e, i, OMEGA, omega, tetta)

r, v = keplerian2cartesian_alt([...])
```

And finally, if you want to try more optimal strategies, maybe you can try to change the argument of perigee using continuous thrust:

https://docs.poliastro.space/en/latest/safe.html#poliastro.twobody.thrust.change_argp.change_argp
https://docs.poliastro.space/en/latest/user_guide.html#studying-artificial-perturbations-thrust

**Comment by Tarlan0001** [comment]
Thanks for recommendations!

How did you plot this?
I tried, nothing happens..

```
from astropy import units as u
from poliastro.plotting import OrbitPlotter
from poliastro.twobody import Orbit
from poliastro.twobody import Orbit
from poliastro.core.elements import coe2rv

Earth_k_val = Earth_k.decompose([u.m, u.s]).value

def keplerian2cartesian_alt(kepler):

    a=(kepler[0]+kepler[1]+Req*2)*1000/2  # m
    e=(kepler[0]-kepler[1])/(kepler[0]+kepler[1]+Req*2)
    i=kepler[2]
    OMEGA=kepler[3]
    omega=kepler[4]
    tetta=kepler[5]

    p = a * (1 - e ** 2)

    return coe2rv(Earth_k_val, p, e, i, OMEGA, omega, tetta)

   
op = OrbitPlotter()

r0, v0= keplerian2cartesian_alt([200, 200, 64.3*math.pi/180, 0, 310*math.pi/180,0])
r1, v1= keplerian2cartesian_alt([8000, 200, 64.3*math.pi/180, 0, 310*math.pi/180,math.pi])
r2, v2= keplerian2cartesian_alt([8000, 600, 64.3*math.pi/180, 0, 310*math.pi/180,math.pi])

o0=Orbit.from_vectors(Earth, r0*u.km, v0*u.km/u.s)
o1=Orbit.from_vectors(Earth, r1*u.km, v1*u.km/u.s)
o2=Orbit.from_vectors(Earth, r2*u.km, v2*u.km/u.s)

op.plot(o0, label="Initial orbit")
op.plot(o1, label="Transfer orbit")
op.plot(o2, label="Final orbit")
```

**Comment by Juanlu001** [comment]
If you try that from a script, you are missing this:

```
import matplotlib.pyplot as plt
plt.show()
# plt.savefig("figure.png")  # Alternatively
```

**Comment by Tarlan0001** [comment]
Just add this at the end? Now it doesn't show the graphs, only the coordinate system with labels.

**Comment by Tarlan0001** [comment]
Thanks!
