### ISSUE TITLE
New orbit creation methods

### ISSUE THREAD

**Issue by astrojuanlu** [poliastro/poliastro#514]
Ideas:

* [x] Heliosynchronous orbits
* [x] Frozen orbits
* [x] Geosynchronous orbits
* [x] Geostationary orbits

Some of these need extra planetary parameters, such as J2.

**Comment by hrishikeshgoyal** [comment]
@Juanlu001  I'd like to start with Geosynchronous and Geostationary orbits.

**Comment by Juanlu001** [comment]
Related: #526

**Comment by Juanlu001** [comment]
Geostationary orbits were added in #524. It would be nice to extend that method to allow for geosynchronous orbits as well.

**Comment by ChanchalKumarMaji** [comment]
@Juanlu001 will I start working on this Issue ?????

**Comment by Juanlu001** [comment]
@ChanchalKumarMaji sure, do you plan to work on which method in particular?

**Comment by ChanchalKumarMaji** [comment]
I plan to start with heliosynchronous orbits. Any suggesions ?

**Comment by Juanlu001** [comment]
@ChanchalKumarMaji That you take a look at https://github.com/poliastro/poliastro/pull/524 for inspiration, and find out what parameters will you need to compute that.

**Comment by sashank27** [comment]
@Juanlu001 I would like to work on the Heliosynchronous orbits if no one is working on that. Also, what changes are required to add the module of geosynchronous orbits as well?

**Comment by Juanlu001** [comment]
@sashank27 sure, all yours! The only changes we might need are adding new planetary parameters to `poliastro.constants`, the rest should all go to a new `Orbit` classmethod.

**Comment by Juanlu001** [comment]
Sorry, I amend myself: for geosynchronous orbits we don't need a new method, just adding the inclination as parameter to geostationary.

**Comment by Juanlu001** [comment]
Notice that frozen orbits were added by @Meuge at https://github.com/poliastro/poliastro/issues?q=is%3Aissue+is%3Aopen+label%3A%22good+first+issue%22

**Comment by Juanlu001** [comment]
(Fixed link)

**Comment by Juanlu001** [comment]
Reconsidered: this issue is not at all easy.

**Comment by hrishikeshgoyal** [comment]
> Sorry, I amend myself: for geosynchronous orbits we don't need a new method, just adding the inclination as parameter to geostationary.

Would we need eccentricity as well in the parameters?

**Comment by MichaelRThompson** [comment]
> 
> 
> > Sorry, I amend myself: for geosynchronous orbits we don't need a new method, just adding the inclination as parameter to geostationary.
> 
> Would we need eccentricity as well in the parameters?

It depends on who you talk do, but yes, generally speaking the term geosynchronous just means a period of 1 sideral day.  Inclination and eccentricity should both be able to vary.

**Comment by jorgepiloto** [comment]
At least two parameters between `a, ecc and inc` should be selected when solving for a Sun-Synchronous orbit. The non-used one is fixed by the other two according to the following relations:

<img src="https://latex.codecogs.com/gif.latex?a^{\frac{7}{2}}&space;=&space;\frac{-3R_{\bigoplus}^{2}J_{2}\sqrt{\mu}}{2\dot{\Omega}(1&space;-&space;e^{2})^{2}}\cos(i)" title="a^{\frac{7}{2}} = \frac{-3R_{\bigoplus}^{2}J_{2}\sqrt{\mu}}{2\dot{\Omega}(1 - e^{2})^{2}}\cos(i)" />

<img src="https://latex.codecogs.com/gif.latex?ecc&space;=&space;\sqrt{1&space;-&space;\sqrt{\frac{-3R_{\bigoplus}^{2}J_{2}\sqrt{\mu}\cos(i)}{2\dot{\Omega}a^{\frac{7}{2}}}}}" title="ecc = \sqrt{1 - \sqrt{\frac{-3R_{\bigoplus}^{2}J_{2}\sqrt{\mu}\cos(i)}{2\dot{\Omega}a^{\frac{7}{2}}}}}" />

<img src="https://latex.codecogs.com/gif.latex?inc&space;=&space;\arccos{\left&space;(&space;\frac{-2a^{\frac{7}{2}}\dot{\Omega}(1-e^2)^2}{3R_{\bigoplus}^2J_{2}\sqrt{\mu}}&space;\right&space;)}" title="inc = \arccos{\left ( \frac{-2a^{\frac{7}{2}}\dot{\Omega}(1-e^2)^2}{3R_{\bigoplus}^2J_{2}\sqrt{\mu}} \right )}" />

Since two variables determine the third one, this can be represented by a surface in space. The following image correspongs to Vallado:

![vallado](https://user-images.githubusercontent.com/28702884/62356587-b65b0280-b511-11e9-8e90-4d0e43408d66.png)

Therefore, the goal is how to deal with the three posibilities when the user callls the method. Do you have any idea about how to manage these different input arguments?

**Comment by Juanlu001** [comment]
@jorgepiloto late answer to your question: I think we can follow the same logic we applied to Sun-synchronous orbits, and check that exactly 2 out of 3 parameters must be not-`None`.

**Comment by jorgepiloto** [comment]
Just found an interesting explanation on geostationary and geosynchronous orbits from Celestrack web page, here is the [link to the post](https://www.celestrak.com/columns/v04n07/).

**Comment by astrojuanlu** [comment]
The last step for this was closed in #965 :tada: Thanks all!
