### ISSUE TITLE
Poliastro installation in Anaconda3 environment under Windows 10

### ISSUE THREAD

**Issue by framaggi55** [poliastro/poliastro#546]
Hi everybody!
in a precedent issue (#544) I wrote about some problems in Poliastro's testing. I have a Windows 10 workstation, where I installed as first the Anaconda3 ecosystem. Testing the program after the installation I have hade some discrepances, and Juan Luis replied to me writing "there's a floating point difference of about 1e-16 from the expected value. The root cause is probably that you are using MKL and I always use OpenBLAS, but as I understand that your environment might be a big fragile (it's not easy to install tensorflow in Windows...) it's safe to leave it like that".
In fact, in the Anaconda3 environment I had installed a lot of stuff for Machine Learning, including Tensorflow and Keras, but but worried about what Juan Luis had written about the fragility of my environment, and wanting to try using OpenBLAS rather than MKL, I uninstalled everything and started a new installation trying to base it on the use of OpenBLAS.
So I installed the version of NumPy based on blas 1.1 and openblas 0.3.3. At this point, however, I encountered a problem: among the dependencies of Poliastro there is scipy, whose use is in turn bound to the presence of blas in its MKL version... So, in fact, I can't reinstall Poliastro!
At this point, to be able to use the program, I think I have to go back to installing the libraries based on MKL, and I wonder: how does Juan Luis make Poliastro run under OpenBLAS? The only explanation I can give is that he's using an operating system other than Windows 10, and in fact it's mainly to ask him this that I'm opening this new issue ...

**Comment by Juanlu001** [comment]
Salve @framaggi55!

Perhaps the key is that I am mostly using packages from [https://conda-forge.org/](conda-forge). conda-forge is a "community channel" for conda packages: they focus on reproducible builds, and have a highly sophisticated automated process for anybody to contribute conda packages. NumPy from conda-forge is compiled against OpenBLAS by default, which as you can see is available in Windows as well:

https://anaconda.org/conda-forge/openblas

To test that you can actually do it, instead of reinstalling everything from scratch, I recommend you the following:

1. Create a new conda environment. conda environments are a simple way of having simultaneous Python installations, all independent from each other. From the command line, you can do `conda create -n poliastro_test python=3.7 --channel conda-forge`.
2. Do `activate poliastro_test` to activate the environment. Now all the `conda install` commands won't affect your `base` or `root` environment, only this one.
3. `conda install numpy openblas scipy --channel conda-forge` should install a NumPy based on OpenBLAS.
4. `conda install poliastro --channel conda-forge` will continue using the dependencies installed in the previous step.

I don't have a Windows machine at hand, so if you try this please tell me how it ended.

**Comment by framaggi55** [comment]
Hi, Jan Luis!
so as I had imagined, you're using an operating system other than Windows 10...
Do you think I haven't tested all the passages you mentioned, before to open a new issue? ;-)
The fact is that for Windows environment, at this moment, there is NO scipy version available in conda-forge! Don't you believe me? Try to read here: https://github.com/conda-forge/scipy-feedstock.
In addition, at the moment I am trying to experiment with other libraries, which would even seem to offer greater calculation precision, as like mpmath ... the problem is to be able to run Poliastro in Windows without having to give into the Intel's blackmail, being forced to accept its MKL as the last chance!!!

**Comment by Juanlu001** [comment]
Oh, you're right! I forgot about that...

Well, then we have no option than waiting for the brave conda-forge developers to fix the scipy feedstock. And yes, accept MKL at least for now.

> so as I had imagined, you're using an operating system other than Windows 10...

Yes, I'm a Linux advocate :)

Should we close this issue then?

**Comment by framaggi55** [comment]
Yes, Juan Luis, we can close the issue... could I hope, however, to find some other madman who, like me, is trying to use Poliastro under Windows 10, to have someone to compare?!? ;-)

**Comment by Juanlu001** [comment]
Those are rare :stuck_out_tongue_closed_eyes: but my recommendation is to [ask in our chat](https://riot.im/app/#/room/#poliastro:matrix.org)!
