### ISSUE TITLE
plotly requires ipywidgets.  But this isn't captured in dependencies.  Perhaps add to requirements? 

### ISSUE THREAD

**Issue by jimmyz70** [poliastro/poliastro#548]
poliastro install on Mac OS X fails tests.  Traced to plotly depending upon FigureWidget.  This is found in ipywidgets.  Which doesn't get installed during poliastro install.  Can this be fixed simply by adding ipywidgets to requirements.txt?

Solution:
My solution was to use pip to manually install ipywidgets. 
After that I still had to update matplotlibrc to use TKAgg since python isn't installed as a framework on my Mac.
With those two changes I was able to pass the tests. (With 55 warnings.  Mostly about date conversions.)

**Comment by Juanlu001** [comment]
Hi @jimmyz70, thanks a lot for reporting this issue!

You are totally right: [plotly depends only on nbformat](https://github.com/plotly/plotly.py/blob/v3.5.0/setup.py#L288), which in turn [only depends on jupyter-core](https://github.com/jupyter/nbformat/blob/4.4.0/setup.py#L94).

From my understanding, in the same way that we don't want poliastro to depend on the Jupyter notebook explicitly (since there are people using it without the notebook), I guess plotly.py is in the same situation.

However, I understand that this makes the installation for the notebook more complicated, and that those extra steps are not documented. Therefore, I'm labeling this as a bug in the documentation.

Also:

> After that I still had to update matplotlibrc to avoid use TKAgg since python isn't installed as a framework on my Mac.

Could you please detail what are those steps? I am not familiar with OS X.

>  With those two changes I was able to pass the tests. (With 55 warnings. Mostly about date conversions.)

Yes, there are too many warnings [and we want to suppress them](https://github.com/poliastro/poliastro/issues/499) to reduce the testing noise.

**Comment by Juanlu001** [comment]
By the way, we don't use `requirements.txt` files so with your permission I will edit the issue title.

**Comment by Juanlu001** [comment]
My idea is to provide a `pip install poliastro[jupyter]` that brings all the necessary stuff to work with poliastro in Jupyter notebook (and to a certain extent, JupyterLab).

**Comment by Juanlu001** [comment]
I have been bitten by this today while testing the new beta version. Working on a fix.
