### ISSUE TITLE
Installation in venv fails tests: ImportError: cannot import name 'FigureWidget'

### ISSUE THREAD

**Issue by NoraCodes** [poliastro/poliastro#629]
🐞 **Problem**

Installing via pip in a venv fails because not all requirements are specified in the package.

When installing in a Python 3.6.7 venv using Pip 9.0.1, running `./venv/bin/python -c "import poliastro.testing; poliastro.testing.test()"` fails with a bunch of tracebacks amounting to `ImportError: cannot import name 'FigureWidget'`.

This is the same as santosjorge/cufflinks#130.

🎯 **Goal**

Poliastro doesn't work when installed from Pip, and it should.

💡 **Possible solutions**

Very easy to solve: add ipython and ipywidgets to your requirements. I have tested this solution and it works on the version I specified.

**Comment by Juanlu001** [comment]
Hi @noracodes, thanks for reporting this issue!

Unless we missed something, the official way of installing poliastro with pip is

```
$ pip install poliastro[jupyter]
```

as specified in the https://docs.poliastro.space/en/stable/getting_started.html#alternative-installation-methods 

(which is the only place that mentions pip)

However, I understand that people browsing PyPI will be tempted to copy paste `pip install poliastro`, or perhaps they just heard about the package and will try the most common thing. Therefore, rather than including those in the mandatory requirements, I think we should make poliastro work even when `FigureWidget` cannot be imported, by being careful with imports and skipping tests where appropriate.

**Comment by NoraCodes** [comment]
> Unless we missed something, the official way of installing poliastro with pip is
> ```
> $ pip install poliastro[jupyter]
> ```
> as specified in the https://docs.poliastro.space/en/stable/getting_started.html#alternative-installation-methods

Understood. I didn't realize that, sorry!

Is it possible that I've misunderstood the use case for the library? I'm planning to write a command line application that generates plots to image files, without ever touching an interactive interface. So far, poliastro seems to work great for this.

**Comment by Juanlu001** [comment]
> Is it possible that I've misunderstood the use case for the library? 

Not at all! We are still focused on interactive visualization and easy API. But we want to make it easier for people doing "just" number crunching :)

> I'm planning to write a command line application that generates plots to image files, without ever touching an interactive interface. So far, poliastro seems to work great for this.

That sounds awesome! In case it's useful, the `StaticOrbitPlotter` produces matplotlib images (only 2D though) so it might be a good fit. On the other hand, if you want to use `OrbitPlotter2/3D`, the blessed solution is probably orca:

https://github.com/plotly/orca#linux-troubleshooting-headless-server-configuration

**Comment by NoraCodes** [comment]
Awesome, good to hear. For now `StaticOrbitPlotter` is working great but I'll keep Orca in mind if I need 3D plots!

**Comment by Juanlu001** [comment]
Excellent! Please keep us posted if you publish that tool somewhere :)
