### ISSUE TITLE
Stop testing on Windows, recommend WSL2

### ISSUE THREAD

**Issue by astrojuanlu** [poliastro/poliastro#666]
As per title.

https://devblogs.microsoft.com/commandline/announcing-wsl-2/

**Comment by Juanlu001** [comment]
https://youtu.be/7-iRf9AWoyE

**Comment by Juanlu001** [comment]
To clarify: WSL2 will be publicly available at the end of the year.

**Comment by danlub** [comment]
I think that could leave users without access to poliastro.
For example, I know of an undetermined number of private companies (not going to provide names) that getting access to WSL right now is only provided if strictly necessary (very senior personnel, admin access, etc) for security reasons.
Those are my two cents

**Comment by Juanlu001** [comment]
I get your point @danlub, and I have worked in companies with such "situations" in the past :)

However, this would only affect our Continuous Integration efforts - poliastro is a pure Python package and it's supposed to work everywhere, anyway. In fact, we provide `noarch` conda packages and universal wheels on PyPI, and we will continue to do so. We would not, in any way, remove the possibility of installing poliastro on Windows. Rather, we'd recommend it for those that can use it for a better experience.

On the other hand, if companies want to collaborate with poliastro, there will be a `Sponsor` button soon :wink: https://github.com/poliastro/poliastro/pull/489

**Comment by danlub** [comment]
Got it! Thanks for the clarification!
I've misunderstood the title then

**Comment by Juanlu001** [comment]
Fair enough, changed the title as well!

**Comment by astrojuanlu** [comment]
> WSL2 will soon be officially available as part of Windows 10, version 2004

2020-03-13

https://devblogs.microsoft.com/commandline/wsl2-will-be-generally-available-in-windows-10-version-2004/

**Comment by astrojuanlu** [comment]
Windows 10 version 2004 was released yesterday https://docs.microsoft.com/en-us/windows/whats-new/whats-new-windows-10-version-2004#windows-virtual-desktop-wvd

**Comment by s-m-e** [comment]
Be careful with relying on WSL 2 - it's built on Hyper V, i.e. virtualization. If you want to run a WSL-2-enabled Windows system inside another virtualization software, it wont work in all cases ("nested virtualization"), also see [here](https://docs.microsoft.com/en-us/windows/wsl/wsl2-faq#will-i-be-able-to-run-wsl-2-and-other-3rd-party-virtualization-tools-such-as-vmware-or-virtualbox).

**Comment by astrojuanlu** [comment]
True that @s-m-e, however I guess that users running a virtualized Windows should be able to run Linux somehow? (I might be wrong on this)

**Comment by astrojuanlu** [comment]
By the way, status updates in https://docs.microsoft.com/en-us/windows/release-information/status-windows-10-2004. From what I understand, the rollout is being slow but steady.

There were some interesting changes in June https://devblogs.microsoft.com/commandline/gpu-compute-wsl-install-and-wsl-update-arrive-in-the-windows-insiders-fast-ring-for-the-windows-subsystem-for-linux/ namely, WSL2 by default and easier install. But these are only for insiders at the moment, IIUC.

Hopefully later this year we will be able to take this more seriously.

**Comment by danlub** [comment]
This is great news! WSL is not as good as a full linux 😉 but it a nice thing to have when stuck with Windows

**Comment by astrojuanlu** [comment]
> Support for Windows Subsystem for Linux (WSL) 2 distros is being backported to Windows 10 version 1903, and 1909!

https://devblogs.microsoft.com/commandline/wsl-2-support-is-coming-to-windows-10-versions-1903-and-1909/

(arrived from https://www.omgubuntu.co.uk/how-to-install-wsl2-on-windows-10)

**Comment by astrojuanlu** [comment]
I've been told on social media that WSL2 is working quite well and it's easy to install :) See replies to https://twitter.com/poliastro_py/status/1367768123022180353

**Comment by Chainesh** [comment]
@astrojuanlu Yes it is working quite well, I am using Ubuntu in WSL2 since a month.

**Comment by xlxs4** [comment]
@astrojuanlu:
I think what you must mainly factor in is the user base poliastro has, or the one you want it to have. I'm guessing you'd like it to be easily accessible for all, if possible. With that in mind:
1. WSL2 is in a great state right now, and very easy to set up/work with; There's a significant portion of Windows devs that use VSCode, and things like https://code.visualstudio.com/docs/remote/wsl make it even easier. Additionally, I think Microsoft really wants to lure in users to work on Windows with linux :tm: inside (see powertoys, windows terminal, wsl2, and so on); meaning that the support and the overall experience will likely get better as time progresses.
2. There are people (myself included) that might have/want to be on Windows for particular reasons. These users will probably be able to deal with using WSL2, or will be using it already.
3. If the people above don't want to go the WSL route, they will probably be able to work around the potential Windows quirks and still use poliastro just fine. I think this is an important point to stress.
4. Inexperienced users on Windows are still more than likely to be using poliastro (since they might be astrophysicists or, generally, from a discipline where you don't often expect someone to be versed in debugging potential issues/using linux/etc.). These users will want an out-of-the-box experience. Poliastro will keep working fine on Windows nonetheless, and conda(-forge) is here for the rescue. **Note**: the potential issues on Windows will almost certainly not have to do with poliastro itself. They might have to do with stupid ABIs, dependencies gone rogue, etc. _You'll hardly, if ever, catch these issues during CI/CD. If they do arise, they depend heavily on the specific use case/environment/OS build of the end user_. To sum up, inexperienced users on Windows will be able to still use poliastro just fine; if something occurs, it will mostly be very specific and that's what the issue tracker is for, either way.

In my opinion testing on Windows doesn't really achieve that much. I would propose you go forward with recommending WSL2. To make things even better, not just drop a line saying "For a better experience use poliastro through WSL2", but go the extra step and add proper documentation to help a user setting this up (or at least point to the already-existing one). If you want, you can also add a small section with solutions for the most common issues people can face on Windows (to be discovered and updated through the issue tracker).  For an example, you can let people know pywin32 can need installing, or that pillow and numpy are often weird, or that constraining the SAT solver when installing for conda with a `python=xyz` can go a long way, etc.

**Comment by astrojuanlu** [comment]
Thanks a lot for your thorough response @xlxs4 !

**Comment by astrojuanlu** [comment]
As part of our efforts in 0.16 to improve our installation documentation, I propose that we:

- Add a mention to WSL2 in 0.16
- Make 0.17 the last release to be natively tested on Windows
- After 0.17 is released, remove Windows from the CI

Again, this should not impact users significantly, since poliastro is a pure Python package and all its dependencies are well tested in all operative systems.

**Comment by astrojuanlu** [comment]
Been thinking a lot about this lately. Going back to what @xlxs4 said:

> the potential issues on Windows will almost certainly not have to do with poliastro itself. They might have to do with stupid ABIs, dependencies gone rogue, etc. You'll hardly, if ever, catch these issues during CI/CD. If they do arise, they depend heavily on the specific use case/environment/OS build of the end user. To sum up, inexperienced users on Windows will be able to still use poliastro just fine; if something occurs, it will mostly be very specific and that's what the issue tracker is for, either way.

Indeed, poliastro is a Python package, and our CI rarely catches OS-specific problems. Rather, it tends to catch some noise :) like tiny floating point differences and things like that.

I'm going to remove Windows and macOS from the CI - at the same time, we are _totally_ keeping support for these systems! It's just that we will save some CI time and CO2 by assuming that things will work mostly the same in all operative systems.
