### ISSUE TITLE
izzo.lambert function with custom gravity

### ISSUE THREAD

**Issue by Tarlan0001** [poliastro/poliastro#677]
I need to solve the lambert problem, however, I have a custom gravity model.

`izzo.lambert(Earth.k, r0, r, tof)` needs `Earth.k` parameter. May I change it, adding own ODE of motion?

My ODE of motion:
```
# ODE solver
function ode_solve(dy,y)
	r=(y[1]^2 + y[2]^2 + y[3]^2)
        n=1/(r^3+r^2+r)

	dy[1] = y[4]
	dy[2] = y[5]
	dy[3] = y[6]
	dy[4] = -y[1]*n/r
	dy[5] = -y[2]*n/r
	dy[6] = -y[3]*n/r
end
```

**Comment by Juanlu001** [comment]
Hi @Tarlan0001, thanks for your interest in poliastro!

What you describe is very interesting, but requires a bit of work. In the Vallado algorithm, the `k` parameter is used to compute the time of flight:

https://github.com/poliastro/poliastro/blob/ec2dc04ad23ebdebf4345630c93eb628365c4002/src/poliastro/core/iod.py#L138

The Izzo algorithm is a bit more complicated because it uses a dimensionless representation of it:

https://github.com/poliastro/poliastro/blob/ec2dc04ad23ebdebf4345630c93eb628365c4002/src/poliastro/core/iod.py#L224-L228

Therefore, you would need to modify the algorithms to use the custom gravity model that you describe to compute the time of flight. All the rest can remain the same. I recommend you to start with Vallado, and try to validate that with some external source.

If you need help, I encourage you to join our chat:

https://chat.openastronomy.org/#/room/#poliastro:matrix.org

Best luck!

**Comment by Tarlan0001** [comment]
Well, ODE of motion arount the Earth is (if we consider only central gravitational force): 
```
function ode_solve(dy,y)
	r=(y[1]^2 + y[2]^2 + y[3]^2)
        #myu- gravittional parameter

	dy[1] = y[4]
	dy[2] = y[5]
	dy[3] = y[6]
	dy[4] = -y[1]*myu/r
	dy[5] = -y[2]*myu/r
	dy[6] = -y[3]*myu/r
end
```
Isn't it?

In my case, `myu=1/(r^3+r^2+r)`
How may I change?


P.S I know, that this is not your problem, however, I need to solve this asap :)

**Comment by Juanlu001** [comment]
> How may I change the labmert.izzo() function?

Do you need the Izzo method? (The other one does not support multi revolution but it's simpler)

I don't know the details but somehow you have to derive the **time of flight** from your equations. For the normal gravity there is an analytical solution (the Kepler's equation), for yours you will probably need to iteratively solve the differential equation. Bear in mind that the normal solving process is giving the time of flight and computing the position, but in this case you want to do the other way around.

**Comment by helgee** [comment]
x-ref: https://github.com/JuliaSpace/SatelliteToolbox.jl/issues/29

**Comment by Tarlan0001** [comment]
I chose the Izzo method due to its accuracy and performance. The BVP solver works too long and not very accurate.

May create a new body in poliastro.bodies, like Earth and Sun, and write the custom equation of motion?

**Comment by Juanlu001** [comment]
> and write the custom equation of motion?

You already have the equations of motion (mostly translating your first code snippet to Python). As I said, the key here is to derive the time of flight from them.

**Comment by Juanlu001** [comment]
xref https://space.stackexchange.com/q/36315/10716

**Comment by Tarlan0001** [comment]
I mean, may I create another object, different from Earth, with a custom gravity, using the mentioned ODE?

BTW, time of flight (tof) is an input parameter to the izzo.lambert function. Is it different from what you mean?

**Comment by Juanlu001** [comment]
> I mean, may I create another object, different from Earth, with a custom gravity, using the mentioned ODE?

I don't think you need it

> BTW, time of flight (tof) is an input parameter to the izzo.lambert function. Is it different from what you mean?

Yes, the _target_ time of flight it's an input, but also it's a value it's iterated on inside the algorithm.

**Comment by Tarlan0001** [comment]
Could you please explain, why I don't need to create another object?
My equation of motion is different from the objects of the Solar system...

**Comment by helgee** [comment]
@Tarlan0001 I think it would be really helpful if you could give us a little context. What high-level problem are you actually trying to solve? Is this about the perturbed Lambert problem? What are your inputs and what are the expected outputs?

**Comment by Juanlu001** [comment]
> Could you please explain, why I don't need to create another object?

The `Body` objects only carry metadata about the planets: their mass, radius, gravitational constant... The equations of motion are not involved.

The only place in poliastro where the equations of motion are explicitly used is in the Cowell propagation method:

https://github.com/poliastro/poliastro/blob/ec2dc04ad23ebdebf4345630c93eb628365c4002/src/poliastro/core/propagation.py#L10-L35
https://github.com/poliastro/poliastro/blob/ec2dc04ad23ebdebf4345630c93eb628365c4002/src/poliastro/twobody/propagation.py#L70

In the `poliastro.iod` algorithms the equations of motion are never imported. Why? Because the algorithms already "distilled" the numerical solution for the time of flight from the standard equations.

Therefore, if you put your equations _somewhere_ it's not going to make any difference. Someone has to rewrite the Vallado and Izzo algorithms in a way that they use _your_ equations of motion.

**Comment by helgee** [comment]
See here for example: http://epubs.surrey.ac.uk/844973/1/main%20%28002%29.pdf

**Comment by Tarlan0001** [comment]
@helgee @Juanlu001 
Well, in my research I'm studying the problem of rotation of the Sun around the center of Milky Way. For the beginning, I got the mentioned ODE of motion. It's a little bit different from the simple Newtonian gravity.

I understand that this is impossible currently by means of poliastro. But, probably, you would give me a clue to the quick and accurate solution of BVP? 

For example, currently in Julia I'm using the following BVP solver (but it's slow and I think that the solution is not optimal):
```
function lambert(y0,init_val,t0,t1)  #t in Myr, y0 in km and km/s

	t0=t0*Myr #sec
	t1=t1*Myr #sec
    tspan = (t0,t1)

	function bc!(resid,sol,p,t)  
	  resid[1] = sol[1][1]   - init_val[1]
	  resid[2] = sol[1][2]   - init_val[2]
	  resid[3] = sol[1][3]   - init_val[3]
	  resid[4] = sol[end][1] - init_val[4]
	  resid[5] = sol[end][2] - init_val[5]
	  resid[6] = sol[end][3] - init_val[6]
	end

    ### Now use the BVP solver to get closer
	bvp = TwoPointBVProblem(ode_solve, bc!, y0, tspan)
    sol = solve(bvp, Shooting(Vern9()),abstol=1e-12,reltol=1e-12)

    return [sol[1][4],sol[1][5],sol[1][6],sol[end][4],sol[end][5],sol[end][6]]
end
```

**Comment by astrojuanlu** [comment]
@Tarlan0001 in your last code sample you have the equations of motion and a BVP solver, so unless there's something wrong I think it should be enough to find a solution. I can't bring zero help with the analysis of the optimality of it, since I am only familiarized with usual Newtonian dynamics. Regarding the code, I know that [in SciPy there is only one BVP algorithm](https://docs.scipy.org/doc/scipy/reference/generated/scipy.integrate.solve_bvp.html), perhaps there are other libraries with richer capabilities. And finally, as I stated before this is probably out of scope for poliastro, or at least I don't think we are adding something like this within 3 years.

Therefore, I am closing this issue, but feel free to continue discussing or opening a new one.
