### ISSUE TITLE
Fill __all__ variable for packages/subpackages

### ISSUE THREAD

**Issue by noc0lour** [poliastro/poliastro#773]
Currently the `__all__` variable in the top-level `__init__.py` is not filled and thus autocompletion only works for some submodules.  Adding classes & functions that should be visible from the commandline/autocompletion would be beneficial for development.

💡 **Feature request**

In the top-level `__init__.py` add the subpackages & submodules that are available. For subpackages add functions & classes that are not visible yet and have to be exported to the `__all__` variable in the respective `___init__.py`

🎯 **Goal**

Working and reliable autocompletion & autodiscovery across different Python IDEs.

**Comment by Juanlu001** [comment]
Hi @noc0lour, thanks for your interest in poliastro and sorry for the delay!

We currently don't expose any functions or classes in the top-level `__init__.py`, that's why it's empty. Nowadays the user is expected to import each submodule to access things like `Orbit`. We make one exception to allow `from poliastro.twobody import Orbit` instead of `poliastro.twobody.orbit import Orbit` and therefore we have:

https://github.com/poliastro/poliastro/blob/30a3cb645985d8b5fab1f0e09b620f941a9e093d/src/poliastro/twobody/__init__.py#L1-L3

Can you specify a little bit more how autocomplete is failing, or in which specific cases?

**Comment by noc0lour** [comment]
No problem, right now I can't recall why I added these changes locally, but I've kept them in my stash for a while and had to problems without them. Maybe I recall at some point why I thought it's useful, but both, `ipython` and `anaconda` are able to resolve modules in the `poliastro` package now. 

```
"""
=========
poliastro
=========

Utilities and Python wrappers for Orbital Mechanics

"""

__version__ = "0.13.post0.dev0"

from . import (
    bodies,
    cli,
    constants,
    coordinates,
    ephem,
    frames,
    integrators,
    iod,
    maneuver,
    neos,
    plotting,
    spheroid_location,
    threebody,
    twobody,
    util,
)

__all__ = [
    "bodies",
    "cli",
    "constants",
    "coordinates",
    "ephem",
    "frames",
    "iod",
    "integrators",
    "maneuver",
    "neos",
    "plotting",
    "spheroid_location",
    "threebody",
    "twobody",
    "util",
]
```

**Comment by Juanlu001** [comment]
Fair enough, let's close this issue them. Thanks anyway!
