### ISSUE TITLE
Errors Testing poliastro 0.4

### ISSUE THREAD

**Issue by OrbitalMechanic** [poliastro/poliastro#92]
I'm running Python 2.7.x on a MacBook Pro running Mac OS X 10.11.2 (El Capitan) under the Anaconda distribution. The installation was successful, however when I ran the test command line string,

python -c "import poliastro; poliastro.test()"

I got error message during "collecting tests/test_ephem.py" and failure during "test_body_printing_has_name_and_symbol." The error messages were captured in the attached file to this note.

Any Advice?

Sam Dupree.
[poliastro-0.4_tests.txt](https://github.com/poliastro/poliastro/files/70483/poliastro-0.4_tests.txt)

**Comment by Juanlu001** [comment]
Hello Sam, thanks again for your early input. You actually installed the development version (I know this because the string `poliastro-0.5.0.dev0` appears in the tests), and it no longer supports Python 2. That's why those two tests are failing, the rest of the library would work as expected.

I recommend that you either to create a Python 3 environment in Anaconda or you stick to poliastro 0.4:

https://github.com/poliastro/poliastro/releases/tag/v0.4.0

Closing this as a non-issue, feel free to reopen it if more errors appear.
